- layout-templates/endpoint-page-template.html
- layout-templates/form-page-template.html
- layout-templates/success-page-template.html
- src/smbc/components/_header.scss
- Added smbc-header__link--service-name override in header
> feat(DIGITAL-2639): Added smbc class for servicename in header

- src/smbc/components/_panel.scss
- Added class for smbc-panel__body
> feat(DIGITAL-2465): Added class for body text within panel

- src/components/file-upload/file-upload.js
- Change document.getElementById to document.getElementsByClassName for next button
- fixed issue with findRecursively returning undefined
> feat(DIGITAL-2450): updated fileupload to targetClassName for nextbutton, fixed findRecursively

- src/components/maps/_base.scss
- src/components/maps/_controls.scss
- src/components/maps/_popups.scss
Changed map container div name and css selector to .smbc-map__container.
Set height of container to 500px
> fix(DIGITAL-2781)- changed map container name, set div height

- src/all.scss
- src/components/_all.scss
- src/components/panel/_index.scss
- src/overrides/_all.scss
- src/overrides/_typography.scss
- Added panel warning (smbc-panel--error)
- Added typography override for font colour white (smbc-!-font-color-white)
> feat(DIGITAL-3034): Added panel warning and font colour override

- package-lock.json
- package.json
Updated project dependency govuk-frontend to 3.9.0
> chore(package): updated govuk-frontend to 3.9.0

- src/components/_all.scss
- src/components/error-message/index.scss
> feat(errorbase): created smbc error-message

- src/all.js
- src/components/file-upload/multiple-file-upload.js
add js so that an error is displayed if the file or files selected are bigger than 23MB
> feat(multiple-file-upload): add js to show error for files if too big

- src/components/_all.scss
- src/components/footer/_index.scss
- src/components/input/_index.scss
> chore: add styling for file upload

- src/components/file-upload/multiple-file-upload.js
Update js to fix the error message sidebar
> chore: fix red side bar for error message inside the javascript file

- src/components/input/_index.scss
Added matching right side padding to fix focus
Added box-sizing to stop input pushing outside of parent div
> fix(input): matched padding, added box-sizing

- src/components/button/_index.scss
Changed some button properties for IE11 support
> fix(button): changed properties for IE11 support

- src/components/file-upload/multiple-file-upload.js
Fix so that server error classes are removed
> Fix (multiple file upload): fix issue with residual server error classes

- src/components/file-upload/multiple-file-upload.js
Use provided data attrbute 'data-individual-file-size' for filesize check
> feat(fileupload): get data filesize property for filesize check

- src/components/_all.scss
- src/components/recaptcha/_index.scss
add component for smbc-recaptcha
> feat(recaptcha): add component for recaptcha

- src/components/button/_index.scss
Updated smbc-button-llink hover effect to match link styling
> chore(button): updated smbc-button--link hover

- src/components/file-upload/multiple-file-upload.js
Added fileupload input error classes to $module on error
> fix(fileupload): added input error classes to input

- src/components/_all.scss
- src/components/table/_index.scss
- src/overrides/_typography.scss
Moved wordbreak to override
Deleted table css wordwrap class
> feat(font): created word break override, removed table css

- src/all.js
- src/components/recaptcha/recaptcha.js
Added recaptcha module to update recapcha element attributes to improve accessibility
> feat(recaptcha): js module for accessibility

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- src/components/_all.scss
- src/components/table/_index.scss
Added smbc-table__header, extends off govuk-table with font-weight 400.
Included fix for setup-node action to @v2.1.2
> feat(table): added smbc-table__header

- src/components/calendar/_index.scss
add missing background-color on disabled chevron hover state
> fix(calendar): fix missing chevron disabled background

- package.json
Bump minor version for 1.2.0 release
> chore: version minor bump

- src/core/_typography.scss
Add style for before and after line through text
> Login redesign

- src/all.scss
> fix(fontawesome): fix brand icons not appearing

- src/all.scss
> fix(font awesome): import font awesome regular

- package.json
- src/components/calendar/_index.scss
> fix: calendar merge conflict

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- package.json
Update GitHub action job names and npm test command
> minor: amend GitHub actions job names and npm test command

- src/components/_all.scss
- src/components/add-another/_index.scss
- src/components/button/_index.scss
styling for field set, legend and button
> chore(add another): styling for field set, legend and button

- src/components/button/_index.scss
- src/overrides/_typography.scss
new text-align property add typography
> refactor(alignleft): move into typography

- package-lock.json
- package.json
- src/components/maps/_controls.scss
> fix(map controls): scale font size from 16px to 13.3px to stop iPhone auto focus

- package-lock.json
- src/components/maps/_controls.scss
> refactor(mapControls): use govuk-px-to-rem, fix mismatch version num

- src/components/maps/_controls.scss
Merge leaflet-search styling into Maps _controls.scss
> feat(map search control): add styling for leaflet search

- src/components/maps/_controls.scss
> revert(control): revert changes

- src/components/maps/_index.scss
- src/components/maps/_search.scss
new style class for smbc-map-search 
- incorporates existing bespoke leaflet-search overrides and leaflet-search css
> feat(smbc-map-search): create new map search styling

- src/components/_all.scss
forgot to import component style
> fix(accordion): forgot to import component style

- src/components/maps/_control-layers.scss
- src/components/maps/_index.scss
New classes for styling the smbc-control-layers for maps
> feat(control-layers): add classes for smbc-control-layers

- src/components/maps/_control-layers.scss
- src/components/maps/_search.scss
> refactor(map): use $govuk-font-family

- src/components/accordion/accordion.js
Fix the boolean which was not being set correctly in the private _toggle method. ( I only changed it from being true booleans because the tests failed )
Also removed the param of mouse event, as it could be triggered from mobile too.. just for info sake.
> fix(accordion): toggle boolean not being set right

- .github/workflows/deploy.yml
> fix: amend github actions to correclty get the branch name

- package.json
- src/components/maps/_control-layers.scss
> fix: amend overflow-x for lefalet maps

- src/components/maps/_control-layers.scss
> fix: property order in leaflet controls

- src/components/maps/_search.scss
> fix(search): add missing width on input

- package.json
> chore(version): bump version

- src/components/maps/_search.scss
Reverting previous commit that bypassed develop by accident. Deploy will fail again, but that is expected and will not cause any issues.
> revert(_search): revert previous commit

- package.json
> chore: increment patch

- package-lock.json
- package.json
- src/components/maps/_search.scss
> Bugfix 6645

- package-lock.json
- package.json
- src/components/maps/_control-layers.scss
Changes made to [Jira 6607](https://stockportbi.atlassian.net/browse/DIGITAL-6607) after meeting.
See desired style in comments screenshot... should be a grey box, with a white icon in, essentially.
> fix(6607): using font awesome

- package.json
- src/all-ie8.scss
- src/all.scss
> chore(links): opt in to new link styling

- package.json
- src/components/button/_index.scss
> refactor(smbc-button--link): amend styling for buttons styled as links to match the new agreed styling

- package.json
- src/components/maps/_popups.scss
> fix(popup): add width to header icon to align with popup body

- package-lock.json
- package.json
- src/components/_all.scss
- src/components/notification-banner/index.scss
- src/settings/_typography-font.scss
add new component
add new light-bold variable value
> feat(notification-banner): add overrides for notification-banner

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- tasks/gulp/compile-assets.js
Release Patch to add compression and caching headers to bucket resources - as PR #131
> Release 1.5.2

- package.json
- src/components/_index.scss
Add the smbc-embeddable class with styling to be used on embeddable forms.
> chore(index): add smbc-embeddable tag
